# Generated by Django 2.2.1 on 2019-09-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0002_auto_20190916_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '文章内容'},
        ),
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='images/1.jpg', upload_to='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
    ]
